### ISSUE TITLE
Handle empty return

### ISSUE THREAD

**Issue by mdodge-ecgrow** [qeet/IMPORTJSONAPI#1]
This is a great library!  Seems like it is being updated much more than the other one.

I have a stock API service I am pulling data from.  For some stocks, the data is there and everything works great.  For some, there is no data at all.  When I view the endpoint in the browser, I just view nothing, a blank page.  Then when I click on 'raw data', I just see an empty array `[]`.  So when that gets pulled into my sheet, it looks empty in the cell.  But I am running a formula on that cell: `=IF(ISBLANK(TRIM(C3)), B3*E3, C3*E3)` and for some reason `ISBLANK` is always returning false.  The formula in C3 is: `=IMPORTJSONAPI("https://cloud.iexapis.com/stable/stock/" & A3 & "/dividends/next/?token=" & P$7, "$", "amount")`

Also, here is the returned JSON for a call to the same endpoint that does include data: ```{"exDate":"2020-04-14","paymentDate":"2020-05-15","recordDate":"2020-04-15","declaredDate":"2020-02-20","amount":"1.18","flag":"Cash","currency":"USD","description":"Ordinary Shares","frequency":"quarterly","symbol":"ABBV"}```

**Comment by qeet** [comment]
Glad you find the library useful and thanks for reporting this issue. I think I found the bug and have released a new version of the script (v1.0.1). Please update your copy of the script and let me know if it solves your problem.

**Comment by mdodge-ecgrow** [comment]
I tried it, still not working.  I also tested modifying your code by commenting out `if (table_data.length == 0) {` and the closing `}` and then of course no data comes down, but now my `ISBLANK` check does return true.  So it must not be getting into that if statement.

**Comment by qeet** [comment]
OK second attempt to fix your issue. Try release 1.0.2 and let me know if it works for you.

**Comment by mdodge-ecgrow** [comment]
That did the trick!  Working perfectly now, thanks for your help!
