### ISSUE TITLE
Json import limit error

### ISSUE THREAD

**Issue by wifiuk** [qeet/IMPORTJSONAPI#10]
Is there a limit i can edit to increase this number for the following error:

`text result of importjsonapi is longer than the limit of 50000 characters `

**Comment by qeet** [comment]
No you cannot increase this number. This is a limit imposed by Google Sheets:

https://gsuitetips.com/tips/sheets/google-spreadsheet-limitations/

**Comment by wifiuk** [comment]
ok thanks
