### ISSUE TITLE
Does not receive data with a dot at the end

### ISSUE THREAD

**Issue by scagroup** [qeet/IMPORTJSONAPI#13]
Exemple formula: =IMPORTJSONAPI(R3; "$.RADAR_DATA.PERIODS.*"; "~, @.'Активы', @.'Выручка тек.'")
String @.'Выручка тек.' doesn't work

**Comment by qeet** [comment]
Does it work if you escape the dot with it's hex code? 

`=IMPORTJSONAPI(R3; "$.RADAR_DATA.PERIODS.*"; "~, @.'Активы', @.'Выручка тек%2E'")`

**Comment by scagroup** [comment]
> Does it work if you escape the dot with it's hex code?
> 
> `=IMPORTJSONAPI(R3; "$.RADAR_DATA.PERIODS.*"; "~, @.'Активы', @.'Выручка тек%2E'")`

This doesn't work

**Comment by qeet** [comment]
I setup a small test and I cannot reproduce the problem you describe. Are you able to share any of the source JSON data so I can try and reproduce your issue?

**Comment by scagroup** [comment]
Ok. Link where is the problem https://fin-plan.org/api/techanalysis/getDetailInfo/MOEX_RUS/modify:full/

**Comment by qeet** [comment]
OK thanks for the link. I reproduced the problem and it seems to be that the data has an extra space between 'Выручка' and 'тек'. So you need two space characters between these words not 1 space. Like this:

@.'Выручка[*space*][*space*]тек.'

**Comment by scagroup** [comment]
It's work

> OK thanks for the link. I reproduced the problem and it seems to be that the data has an extra space between 'Выручка' and 'тек'. So you need two space characters between these words not 1 space. Like this:
> 
> @.'Выручка[_space_][_space_]тек.'

**Comment by scagroup** [comment]
Thanks
