### ISSUE TITLE
Formatting data with the API

### ISSUE THREAD

**Issue by moniqueb91** [qeet/IMPORTJSONAPI#25]
Hi, I just started using this script to retrieve info from Instagram. I was using this ImportJSON script, but it stopped working, but luckily I found yours and now I'm able to retrieve data again, thank you so much ! 
The only problem that I have is with formatting. With the previous script, all the data was returned in a table. However, your script, I'm having trouble formatting the data correctly. I have tried several paths, but it just doesn't work the way I want to... 

What am I doing wrong ? 
Thanks in advance

PS : Here's some screenshots and the URL I'm using to retrieve the content

![Capture d’écran (775)](https://user-images.githubusercontent.com/66549922/114266002-25ca0a80-99f4-11eb-9c22-f77064982aa3.png)

URL : https://www.instagram.com/graphql/query/?query_hash=f2405b236d85e8296cf30347c9f08c2a&variables=%7B%22id%22%3A%2226296967056%22%2C%22first%22%3A12%7D

**Comment by qeet** [comment]
Something like this should work:

`=IMPORTJSONAPI("https://www.instagram.com/graphql/query/?query_hash=f2405b236d85e8296cf30347c9f08c2a&variables=%7B%22id%22%3A%2226296967056%22%2C%22first%22%3A12%7D", "$.data.user.edge_owner_to_timeline_media.edges[*]", "node.id, node.owner.username")`

Just modify the last parameter to get the columns you want.

**Comment by moniqueb91** [comment]
Hi, thanks for your help, I managed to retrieve almost everything I was looking for ! 
I'm still struggling with the caption though, I have tried "node.edge_media_to_caption.edges.text", "node.text" "node.edge_media_to_caption.edges", "node.edge_media_to_caption.edges.node.text"  but I can't get it to work...

<img width="937" alt="Capture" src="https://user-images.githubusercontent.com/66549922/114313767-23e96f80-9af8-11eb-82b0-2a82b7f88f52.PNG">

**Comment by qeet** [comment]
Try this:

`node.edge_media_to_caption.edges[0].node.text`

**Comment by moniqueb91** [comment]
It works ! thanks again for your help. 
PS : In case someone else needs it, here's the path to get the date, the url, the description, the like count & the comment count : "$.data.user.edge_owner_to_timeline_media.edges[*]", "node.taken_at_timestamp, node.display_url, node.edge_media_to_caption.edges[0].node.text, node.edge_media_to_caption.edges.node.text, node.edge_media_preview_like.count, node.edge_media_to_comment.count"
