### ISSUE TITLE
Pass hyphen in column name?

### ISSUE THREAD

**Issue by clally1** [qeet/IMPORTJSONAPI#28]
Is there a way to pass a hyphen in a column's name?

I added ["hyphen", /^\-/] to the patterns list which didn't throw an error anymore, but did skip those columns. Any advice greatly appreciated!

**Comment by qeet** [comment]
you can quote the column name with single quotes eg:

`IMPORTJSONAPI("http:...",  "$..", "'col-name-1'")`

**Comment by clally1** [comment]
Worked like a charm! Thanks @qeet!!

**Comment by clally1** [comment]
I wonder if it's possible to do this automatically if a hyphen is detected in a column name?

**Comment by clally1** [comment]
Wow I got it!

**Just need to add: if(input.includes("-")){var input = "\'"+input+"\'"}** directly under **function read_token_(input, i)**
