### ISSUE TITLE
Google Sheets api error.

### ISSUE THREAD

**Issue by nacrealadan** [qeet/IMPORTJSONAPI#3]
Hey when i try to get values from this API : 
https://api.torn.com/torn/?selections=items&key=sjGKkYCzbfOflGjq
Gives me an error on formula .
I want to get all values from this api . Can you help me pls ?

**Comment by qeet** [comment]
Try this:

`=IMPORTJSONAPI("https://api.torn.com/torn/?selections=items&key=sjGKkYCzbfOflGjq", "$.items[*]", "name, description, effect, requirement, type, weapon_type, buy_price, sell_price, market_value, circulation, image")`

**Comment by nacrealadan** [comment]
i still got the error . Do you have discord to show you ?

**Comment by nacrealadan** [comment]
The Chrome V8 its activated to . The code its just copy and paste but i can get anything from it ...

**Comment by qeet** [comment]
What is the error you are getting?

**Comment by nacrealadan** [comment]
Error parsing formula

**Comment by nacrealadan** [comment]
https://docs.google.com/spreadsheets/d/1fxq1DY4l52GJ9h1eyc8MzlUkD748hv7bXBAaY_isDUM/edit#gid=0

**Comment by nacrealadan** [comment]
here is the doc .

**Comment by qeet** [comment]
Strange. I cut out and pasted your exact formula into my spreadsheet and it worked fine.  As the spreadsheet is just a blank test spreadsheet do you mind granting edit access? Then I can investigate further.

**Comment by nacrealadan** [comment]
yeah sure.

**Comment by nacrealadan** [comment]
i've created a new spreadsheet and i got the same error ...

**Comment by nacrealadan** [comment]
I need you're gmail for acces .

**Comment by blissland** [comment]
I just sent you a request for edit access on the test spreadsheet

**Comment by nacrealadan** [comment]
done

**Comment by blissland** [comment]
OK maybe it is a permissions issue. Try this:

Open the script editor and then manually run the IMPORTJSONAPI function from there. Hopefully it will then ask you to accept permissions.

**Comment by nacrealadan** [comment]
i grant permssions .

**Comment by blissland** [comment]
Not sure whats going on. In cell A13 I used the built in importhtml function and that also gives a formula parse error.

**Comment by nacrealadan** [comment]
I've created an ImportJSON script and iserted the formula and works ...

**Comment by blissland** [comment]
OK got it working. I went to File>>Spreadsheet Settings and changed the Locale to United States

See:

[webapps.stackexchange.com/questions/123879/google-sheets-importhtml-parse-error](webapps.stackexchange.com/questions/123879/google-sheets-importhtml-parse-error)

**Comment by nacrealadan** [comment]
OK ... that's intresting ..

**Comment by blissland** [comment]
Sorry wrong link above:

[https://webapps.stackexchange.com/questions/123879/google-sheets-importhtml-parse-error](https://webapps.stackexchange.com/questions/123879/google-sheets-importhtml-parse-error)

**Comment by nacrealadan** [comment]
thx a lot !

**Comment by blissland** [comment]
Just checked and you can keep your default Locale but instead use semi-colon to separate function args: 

`=IMPORTJSONAPI("https://api.torn.com/torn/?selections=items&key=sjGKkYCzbfOflGjq"; "$.items[*]"; "name, description, effect, requirement, type, weapon_type, buy_price, sell_price, market_value, circulation, image")`

I think the ImportJson formula worked because it only had one argument and you did not need to separate.
