### ISSUE TITLE
Import JSON from sheet

### ISSUE THREAD

**Issue by oli** [qeet/IMPORTJSONAPI#34]
Thanks for this function! I’m being _emailed_ JSON output, and would like a way to quickly ingest it into Google Sheets. Is there any chance you could consider an `ImportJSONFromSheet`-style option similar to bradjasper/ImportJSON (which I can’t seem to get to work)?

Thanks, and no worries if you think that’s outside the wheelhouse of IMPORTJSONAPI 😅

**Comment by qeet** [comment]
Hi,

This is not something I plan to implement I'm afraid. However you can use something like this:

https://extendsclass.com/json-storage.html

This allows you to paste your json data and then gives you a http address you can use to import the data via IMPORTJSONAPI

**Comment by qeet** [comment]
Actually I could easily implement this so the first parameter could be a json string: e.g

=IMPORTJSONAPI(A2, "$", "@")

Where cell A2 (or any other cell) contains the JSON data as a string. Would this work for you?

**Comment by oli** [comment]
@qeet That would be perfect! 😍 Thank you for considering this idea 🙇

**Comment by qeet** [comment]
OK. Will try and do this sometime this weekend.

**Comment by qeet** [comment]
@oli It is done.

**Comment by oli** [comment]
@qeet This works perfectly, even when the cell is on another sheet. Thank you so much! 🎉
