### ISSUE TITLE
limited by 3 args when trying to use headers

### ISSUE THREAD

**Issue by mercy** [qeet/IMPORTJSONAPI#4]
Hi. Love the extension of ImportJSON to be able to include basic auth and headers in the import, but I'm getting hung up on 3 arg limit. So far I have: 
=INPUTJSONAPI("https://url", "path", "@")

When I attempt to add any 4th arg sheets informs me of the 3 arg limit, and if I attempt it without the comma I get a parse error. This is what I'm trying to add:
,'headers={"API-KEY" : "key", "API-SECRET" : "secret"}'

I'm new to programming and sheets, so taking a look at the script didn't inform me as to why it wasn't working. Thanks mate

**Comment by qeet** [comment]
Can you try it replacing the double quotes with single quotes and the single quotes with double quotes e.g

    ,"headers={'API-KEY' : 'key', 'API-SECRET' : 'secret'}"
