### ISSUE TITLE
Setting columns to a particular data type

### ISSUE THREAD

**Issue by mfriedma** [qeet/IMPORTJSONAPI#6]
I am pulling stock data with dates and prices.  The problem is that it all comes back as strings instead of dates and numbers so when I try to do things like sums it does not work.

It would be very nice if you had the ability to cast columns of data to numeric or date datatypes.

If you really want to make it good, make it recognize percentages (so 5% becomes .05) and B, M, T so 39.5M becomes 39,500,000.

**Comment by mfriedma** [comment]
BTW, the tool is awesome.  Thanks for writing this.

**Comment by qeet** [comment]
Thanks for the feedback. I don't have time to implement this right now but I will consider it as soon as I have the time.

**Comment by mfriedma** [comment]
What do you think it would take to add the features I mentioned and to start charging for it in Google’s marketplace?

 

Thanks

Michael Friedman

________________________________

Director | Shune River Capital | 顺溪资本

上海市浦东花园石桥路33号花旗集团大厦23楼（200120）

Level 23, Citigroup Tower 33, Huayuanshiqiao Road Pudong, Shanghai 200120, China

m: +86 186 1664 4164 |  <mailto:mfriedma@shunerivercapital.com> mfriedma@shunerivercapital.com

**Comment by qeet** [comment]
Hi Micheal,

Well to add the functionality of casting columns to various types should be straightforward. However to package this function as an add-on in the marketplace would require  more work as I would need to have some sort of user friendly GUI interface and associated documentation, screenshots etc.

**Comment by dimsanchuk** [comment]
Is there any solution for this?
I am getting numerical data from api and trying to plot a graph.

**Comment by qeet** [comment]
I have added support for converting strings to numbers.
