### ISSUE TITLE
Adding cookies

### ISSUE THREAD

**Issue by mariopattan** [qeet/IMPORTJSONAPI#7]
Hi @qeet , I tried your script adding `headers={ 'referer' : 'origin' ` and it worked.

Now I tried to fetch url that requires cookies. I tried to copy the cUrl 

`curl 'https://seller.shopee.co.id/api/marketing/v3/pas/suggest/keyword/?SPC_CDS=b170594b-b97d-4c98-b46a-3817a4476b13&SPC_CDS_VER=2&keyword=&count=100&placement=0&itemid=3327563418' -H 'referer: https://seller.shopee.co.id/portal/marketing/pas/new?pid=3327563418' 

-H 'cookie: SPC_F=B6DG9MuH6tqlCJcD7x4zYX1j1oZ8097d;SPC_EC="PP4R4d/SjONDGHb/QEOY/XPOXw5Tu7aUmm2c+cRWUE9rcKeiu436/tQcUCdXvmqXC1GzRsm5GgEH6tdgpkgLGy7RaXfT1HD0GyaMurb8e3IZpEIZo7Sx8mPJDG6K9tknWB1kZWJQLB4vCwBDpZWpky47GCkpVOzrona1OQR8JZ4="; SPC_SC_TK=6ca4bfc99e8734310995fb64ce6c1046;SPC_SC_UD=17702964;' --compressed`

and I tried to add into the importjsonapi 
`=IMPORTJSONAPI(K4, "$.data[*]", "keyword", "headers={ 'referer' : 'origin','cookie' : 'SPC_F=B6DG9MuH6tqlCJcD7x4zYX1j1oZ8097d;SPC_EC="PP4R4d/SjONDGHb/QEOY/XPOXw5Tu7aUmm2c+cRWUE9rcKeiu436/tQcUCdXvmqXC1GzRsm5GgEH6tdgpkgLGy7RaXfT1HD0GyaMurb8e3IZpEIZo7Sx8mPJDG6K9tknWB1kZWJQLB4vCwBDpZWpky47GCkpVOzrona1OQR8JZ4="; SPC_CT_9d9658d8="1587439461.hxTJLUJRoRytXKniHrrDw0N6S45gCrZATHnQkM1htDU="; SPC_SC_TK=6ca4bfc99e8734310995fb64ce6c1046;SPC_SC_UD=17702964;' }")`

but it returns Formula Parse Error. Any suggestion to add the cookies? 

Thank you

**Comment by qeet** [comment]
You need to escape the double quote (")  characters in your cookie string by replacing them with \%22. Like this:

`=IMPORTJSONAPI(K4, "$.data[*]", "keyword", "headers={ 'referer' : 'origin','cookie' : 'SPC_F=B6DG9MuH6tqlCJcD7x4zYX1j1oZ8097d;SPC_EC=\%22PP4R4d/SjONDGHb/QEOY/XPOXw5Tu7aUmm2c+cRWUE9rcKeiu436/tQcUCdXvmqXC1GzRsm5GgEH6tdgpkgLGy7RaXfT1HD0GyaMurb8e3IZpEIZo7Sx8mPJDG6K9tknWB1kZWJQLB4vCwBDpZWpky47GCkpVOzrona1OQR8JZ4=\%22; SPC_CT_9d9658d8=\%221587439461.hxTJLUJRoRytXKniHrrDw0N6S45gCrZATHnQkM1htDU=\%22; SPC_SC_TK=6ca4bfc99e8734310995fb64ce6c1046;SPC_SC_UD=17702964;' }")`
